# -*- coding: utf-8 -*-
"""AWSKinesis_produtor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lm5wRnkIcWeNB0VkMZuCQK14qHTIadEv

#Primeira etapa do código de ingestão e vigilância com Kinesis
"""

from dotenv import load_dotenv
import os
import boto3
import json

load_dotenv()

cliente = boto3.client('kinesis',
    aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
    region_name=os.getenv('AWS_REGION'))


#Vamos serializar os dados. No registro, terá os dados que quero que seja serializado
#Abaixo os dados são ficticíos.


registro = {'idvendedor': '991', 'nome': 'Ana'}

#Vamos produzir a informação
resposta = cliente.put_record(
    StreamName='stream1',
    Data=json.dumps(registro),
    PartitionKey='1'
)

#Verificando
print(resposta)