# -*- coding: utf-8 -*-
"""AWSKinesis_Consumidor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18fHdmPxd2V86pHge9_GC8czg1iaHdGyS

# Criando o Consumidor
"""
from dotenv import load_dotenv
import os
import boto3
import json

load_dotenv()

cliente = boto3.client('kinesis',
    aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
    region_name=os.getenv('AWS_REGION'))


#Vamos monitorar pra ver se o streaming está produzindo
#Os dados para preencher o shard, foram gerados no primeiro código

shard = cliente.get_shard_iterator(
    StreamName='stream1',
    ShardId='shardId-000000000003',
    ShardIteratorType='LATEST'
)['ShardIterator']

while shard is not None:
  resultado = cliente.get_records(ShardIterator=shard)
  registros = resultado['Records']
  shard = resultado['NextShardIterator']
  for registro in registros:
    print(registro['SequenceNumber'])
    print(registro['ApproximateArrivalTimestamp'])
    print(registro['PartitionKey'])
    print(registro['Data'])

"""Rodando consumidor, ele entrará em modo de 'escuta'; na espera do produtor"""
